### ISSUE TITLE
Update docker image to actual version requested 

### ISSUE THREAD

**Issue by aleksej-kuznecow** [maxpozdeev/mytinytodo-docker#3]
Kindly requested an update for docker image to an actual version.
Published on docker hub is is 1.7.3
Actual is v1.8-beta

**Comment by maxpozdeev** [comment]
Latest stable is 1.7.6. Just updated.

Beta little later.

**Comment by maxpozdeev** [comment]
Beta version is added.

**Comment by aleksej-kuznecow** [comment]
Thank you. The issue can be closed.

**Comment by maxpozdeev** [comment]
Stable v1.8 is published.
